"""''

Revision ID: 1d031dd7508a
Revises: ea4e78adbf3a
Create Date: 2025-05-24 11:48:26.237236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d031dd7508a'
down_revision: Union[str, None] = 'ea4e78adbf3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('contracts', sa.Column('client_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'contracts', 'clients', ['client_id'], ['id'])
    op.drop_column('contracts', 'client_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('client_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'client_id')
    op.drop_table('clients')
    # ### end Alembic commands ###
