"""''

Revision ID: 1f2038addef4
Revises: 1d031dd7508a
Create Date: 2025-05-24 12:29:07.760708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f2038addef4'
down_revision: Union[str, None] = '1d031dd7508a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('wood', 'coal', 'uranium', name='cargotype'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_transit', 'delivered', name='cargostatus'), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('contracts', 'cargo_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('cargo_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_table('cargoes')
    # ### end Alembic commands ###
