"""''

Revision ID: 01ae5dfb03a7
Revises: 56b9ded62f5a
Create Date: 2025-05-24 13:04:45.755468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ae5dfb03a7'
down_revision: Union[str, None] = '56b9ded62f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('contracts', sa.Column('location_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'contracts', 'locations', ['location_id'], ['id'])
    op.drop_column('contracts', 'destination')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('destination', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'location_id')
    op.drop_table('locations')
    # ### end Alembic commands ###
