"""'Tracks table creation'

Revision ID: c84b9a844fb4
Revises: 01ae5dfb03a7
Create Date: 2025-05-24 15:48:21.977108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84b9a844fb4'
down_revision: Union[str, None] = '01ae5dfb03a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=True),
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargoes.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracks')
    # ### end Alembic commands ###
